import { PrismaClient } from '@prisma/client'
import RestaurantNavBar from '../components/RestaurantNavBar'
import Menu from './components/Menu'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Menu - Milestone',
  description: 'Generated by create next app',
}

const prisma = new PrismaClient()

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  })

  if (!restaurant) throw new Error('could not find restaurant')

  return restaurant.items
}

export default async function RestaurantMenu({
  params,
}: {
  params: { slug: string }
}) {
  const menu = await fetchRestaurantMenu(params.slug)

  return (
    <>
      <div className="bg-white w-full rounded p-3 shadow">
        <RestaurantNavBar slug={params.slug} />
        <Menu menu={menu} />
      </div>
    </>
  )
}
