import Header from './components/Header'
import Forms from './components/Forms'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Reservation',
  description: 'Generated by create next app',
}
export default function Reserve() {
  return (
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header />
        <Forms />
      </div>
    </div>
  )
}
